### ISSUE TITLE
Tag commit/release for mortality?

### ISSUE THREAD

**Issue by brews** [ClimateImpactLab/impact-common#14]
Mortality projection is done with commit fcaf2448931a628d79ace7e44ff6bf902de0a2e0. It would be great if we could tag this commit so that it's easier for researchers to access.

Maybe tag that commit as "v0.1.0" and then bump `master` up to v0.2.0 -- to be clear I don't mean tagging a commit "v0.2.0", just update the package version on `master`.

Need to remember if we do bump master, be sure to update the version in setup.py so that package installs update properly.

**Comment by brews** [comment]
@jrising , I want your "okay" on this if you're available. There might be something at play that I'm not aware of... (Thanks!)

**Comment by jrising** [comment]
Is there a difference in the results if you use `master`? I never put in a tag because I didn't think we had any breaking changes, but if there are now, we should absolutely make one.

**Comment by brews** [comment]
I hear there was trouble through the grapevine but we might want to check this.

**Comment by brews** [comment]
Closing this because mortality has been running on newer versions of this repository.
