### ISSUE TITLE
FutureWarning in gdppc.py

### ISSUE THREAD

**Issue by jrising** [ClimateImpactLab/impact-common#23]
We have this warning coming in:
```
impactcommon/exogenous_economy/gdppc.py:164: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
```

I think all we need is the `value` column.

**Comment by jrising** [comment]
@brews Can I give you this?

**Comment by brews** [comment]
@jrising 👍 Yeah, I can put this on my TODO. If can't solve it we can at least figure out exactly what change is needed.

**Comment by brews** [comment]
Okay, [this change](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.3.0.html#deprecated-dropping-nuisance-columns-in-dataframe-reductions-and-dataframegroupby-operations) in pandas >= v.1.3.0 is the problem. The solution will be subsetting to only "numeric" columns (which are valid in this case) before doing reductions and groupbys.

Edit:

And I think we can do this generally with
```python
df.select_dtypes("number")
```
or
```python
df.select_dtypes(np.number)
```
